# Generated by Django 2.0.6 on 2018-06-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
