# Generated by Django 2.0.6 on 2018-06-03 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0002_auto_20180603_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_time',
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
