# Generated by Django 2.0.6 on 2018-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0005_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
