# Generated by Django 2.0.6 on 2018-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0006_sponsor_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_uri', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=5000)),
            ],
        ),
    ]
