# Generated by Django 2.0.6 on 2018-08-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0007_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
