# Generated by Django 2.0.6 on 2018-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0009_outreachevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
