# Generated by Django 2.0.6 on 2018-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0011_auto_20180818_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subtype',
            field=models.CharField(choices=[('Report', 'Report'), ('Slides', 'Slides'), ('Flysheet', 'Flysheet'), ('Single', 'Single')], default='Single', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Proposal', 'Proposal'), ('PDR', 'PDR'), ('CDR', 'CDR'), ('FRR', 'FRR'), ('PLAR', 'PLAR'), ('Other', 'Other')], max_length=50),
        ),
    ]
