# Generated by Django 2.0.6 on 2018-08-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslt', '0012_auto_20180818_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
